## K fold cross validation
In k-fold cross validation , we split the dataset into "k" number of folds (subsets).
one chunk of data is used as test data for evaluation and the remaining part of the data is used for traininng the model .
Each time , a different chunk will be used as the test data.

## Advantages
Better alternative for train-test split when the dataset is small 

Better for multiclass classification problems
more reliable
useful for model selection

## Importing  the dependencies

In [2]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

## Importing the models

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

## Data collection

In [6]:
df =pd.read_csv("heart.csv")

In [7]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [8]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [9]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [10]:
## Checking the distribution of target variable

In [11]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [14]:
## 0- DEfective Heart
## 1- Healthy heart

In [15]:
## Splitting the dataset

x = df.drop(columns= 'target',axis=1)
y = df['target']

In [17]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3
1     37    1   2       130   250    0        1      187      0      3.5
2     41    0   1       130   204    0        0      172      0      1.4
3     56    1   1       120   236    0        1      178      0      0.8
4     57    0   0       120   354    0        1      163      1      0.6
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
298   57    0   0       140   241    0        1      123      1      0.2
299   45    1   3       110   264    0        1      132      0      1.2
300   68    1   0       144   193    1        1      141      0      3.4
301   57    1   0       130   131    0        1      115      1      1.2
302   57    0   1       130   236    0        0      174      0      0.0

     slope  ca  thal
0        0   0     1
1        0   0     2
2        2   0     2
3        2   0     2
4        2   0     2
..     ...  ..   ...
298      1   0     3
299      1   0     3
300      1   2     3
301      1   1     3
302      1   1     2

[303 rows x 13 columns]

In [18]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [19]:
## number of rows and columns in the dataset

df.shape

(303, 14)

In [20]:
## Checking for missing values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [24]:
## Train test split
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify =y ,random_state=3)

In [25]:
print(x.shape,x_train.shape,x_test.shape)

(303, 13) (242, 13) (61, 13)

In [19]:
# list of models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [20]:
# Import all the required models from scikit-learn
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


# list of models
models = [
    LogisticRegression(),
    SVC(kernel='linear'),
    KNeighborsClassifier(),
    RandomForestClassifier()
]

In [36]:
# 1️⃣ Import libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris  # example dataset

# 2️⃣ Load example data (replace with your own dataset)
data = load_iris()
X = data.data
y = data.target

# 3️⃣ Split the data
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4️⃣ Define models
models = [
    LogisticRegression(max_iter=200),
    SVC(kernel='linear'),
    KNeighborsClassifier(),
    RandomForestClassifier()
]

# 5️⃣ Function to train and compare models
def compare_models_train_test():
    for model in models:
        # Train the model
        model.fit(x_train, y_train)
        
        # Evaluate the model
        train_score = model.score(x_train, y_train)
        test_score = model.score(x_test, y_test)
        
        print(f"{model.__class__.__name__}: Train = {train_score:.3f}, Test = {test_score:.3f}")


# 6️⃣ Run the comparison
compare_models_train_test()

LogisticRegression: Train = 0.975, Test = 1.000
SVC: Train = 0.975, Test = 1.000
KNeighborsClassifier: Train = 0.967, Test = 1.000
RandomForestClassifier: Train = 1.000, Test = 1.000

In [52]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

def compare_models_train_test():

  for model in models:

    # training the model
    model.fit(x_train, y_train)
    
    # evaluating the model
    test_data_prediction = model.predict(x_test)

    accuracy = accuracy_score(y_test, test_data_prediction)

    print('Accuracy score of the ', model, ' = ', accuracy)

In [53]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=200)  =  1.0
Accuracy score of the  SVC(kernel='linear')  =  1.0
Accuracy score of the  KNeighborsClassifier()  =  1.0
Accuracy score of the  RandomForestClassifier()  =  1.0

## Cross Validation
Logistic Regression

In [55]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score


cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000), X, y, cv=5)

print(cv_score_lr)

mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)

mean_accuracy_lr = mean_accuracy_lr*100

mean_accuracy_lr = round(mean_accuracy_lr, 2)

print(mean_accuracy_lr)

[0.96666667 1.         0.93333333 0.96666667 1.        ]
97.33

In [56]:
## Support Vector Classifier

In [61]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score


cv_score_svc = cross_val_score(SVC(kernel='linear'), X,y, cv=5)

print(cv_score_svc)

mean_accuracy_svc = sum(cv_score_svc)/len(cv_score_svc)

mean_accuracy_svc = mean_accuracy_svc*100

mean_accuracy_svc = round(mean_accuracy_svc, 2)

print(mean_accuracy_svc)

[0.96666667 1.         0.96666667 0.96666667 1.        ]
98.0

## Creating a function to compare the models

In [63]:
# list of models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [66]:
def compare_models_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, X,y, cv=5)
    
    mean_accuracy = sum(cv_score)/len(cv_score)

    mean_accuracy = mean_accuracy*100

    mean_accuracy = round(mean_accuracy, 2)

    print('Cross Validation accuracies for ', model, '=  ', cv_score)
    print('Accuracy % of the ', model, mean_accuracy)
    print('----------------------------------------------')

In [67]:
compare_models_cross_validation()

Cross Validation accuracies for  LogisticRegression(max_iter=1000) =   [0.96666667 1.         0.93333333 0.96666667 1.        ]
Accuracy % of the  LogisticRegression(max_iter=1000) 97.33
----------------------------------------------
Cross Validation accuracies for  SVC(kernel='linear') =   [0.96666667 1.         0.96666667 0.96666667 1.        ]
Accuracy % of the  SVC(kernel='linear') 98.0
----------------------------------------------
Cross Validation accuracies for  KNeighborsClassifier() =   [0.96666667 1.         0.93333333 0.96666667 1.        ]
Accuracy % of the  KNeighborsClassifier() 97.33
----------------------------------------------
Cross Validation accuracies for  RandomForestClassifier() =   [0.96666667 0.96666667 0.93333333 0.96666667 1.        ]
Accuracy % of the  RandomForestClassifier() 96.67
----------------------------------------------